
services:
  postgres:
    image: postgres:14
    container_name: energy_postgres
    restart: always
    environment:
      POSTGRES_USER: energy_user
      POSTGRES_PASSWORD: energy_pass
      POSTGRES_DB: energy_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - energy-net

  pgadmin:
    image: dpage/pgadmin4
    container_name: energy_pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin1234
    ports:
      - "8082:80"
    depends_on:
      - postgres
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - energy-net

  scraper:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: energy_scraper
    depends_on:
      - postgres
    volumes:
      - .:/app
    environment:
      DB_HOST: energy_postgres
      DB_PORT: 5432
      DB_NAME: energy_db
      DB_USERNAME: energy_user
      DB_PASSWORD: energy_pass
    command: python3 /app/scrape_energy_data.py
    networks:
      - energy-net

volumes:
  pgdata:
  pgadmin_data:

networks:
  energy-net:
    driver: bridge
