version: "3.9"

services:
  postgres:
    image: ankane/pgvector:latest   # ✅ pgvector-ready Postgres
    container_name: energy_postgres
    restart: always
    environment:
      POSTGRES_USER: energy_user
      POSTGRES_PASSWORD: energy_pass
      POSTGRES_DB: energy_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d   # ✅ init scripts
    networks:
      - energy-net

  pgadmin:
    image: dpage/pgadmin4
    container_name: energy_pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin1234
    ports:
      - "8082:80"
    depends_on:
      - postgres
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - energy-net

  scraper:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: energy_scraper
    depends_on:
      - postgres
    volumes:
      - .:/app
    environment:
      DB_HOST: energy_postgres
      DB_PORT: 5432
      DB_NAME: energy_db
      DB_USER: energy_user
      DB_PASS: energy_pass
      OPENAI_API_KEY: ${OPENAI_API_KEY}   # ✅ pulled from .env
    command: python3 /app/scrape_energy_data.py
    networks:
      - energy-net

  dashboard:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: energy_dashboard
    depends_on:
      - postgres
    volumes:
      - .:/app
    environment:
      DB_HOST: energy_postgres
      DB_PORT: 5432
      DB_NAME: energy_db
      DB_USER: energy_user
      DB_PASS: energy_pass
      OPENAI_API_KEY: ${OPENAI_API_KEY}
    command: streamlit run /app/dashboard/app.py --server.port=8501 --server.address=0.0.0.0
    ports:
      - "8501:8501"
    networks:
      - energy-net

volumes:
  pgdata:
  pgadmin_data:

networks:
  energy-net:
    driver: bridge
